version: "3.8"

services:
  client:
    build: ./client/
    ports:
      - "5173:5173"
    volumes:
      - ./client:/usr/src/
    depends_on:
      - webnotes
    command: sh -c "cd /usr/src/ && npm run dev"


  webnotes:
    build: ./server/
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/
    depends_on:
      - postgres
    command: sh -c "cd /usr/src/ && npm run dev"

  postgres:
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres234
      - POSTGRES_DB=notes
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/docker/volumes/dbdata/_data
